language: python
python:
  - "3.6"
install:
  - pip install -r test_reqs.txt
  - pip install coveralls
script:
  - python setup.py flake8
  - python runtests.py
  - coverage run --source=infranil runtests.py
after_success:
  - coveralls
